### ISSUE TITLE
Lab 2: Requirement 2

### ISSUE THREAD

**Issue by javiersim** [GrassLab/osc2021#48]
I have some trouble understanding requirement 2 from lab 2. What are we trying to achieve? From my understanding, we were supposed to implement a boot loader that can load the kernel image into memory in requirement 1, then what else should we put in cpio archive and load into ram disk?

**Comment by t0037799** [comment]
In Lab 2, you can put plain text files inside it only to test the functionality.

In later labs, you'll put some script files, raw binaries, and ELF inside it.
Then, you can test your kernel without manually typing commands.

Finally, if you have any problem with the documentation, please submit issue at  [documentation's repository](https://github.com/GrassLab/NYCU_Operating_System_Capstone/issues).
